### ISSUE TITLE
NodeJS url package only in with-mocks

### ISSUE THREAD

**Issue by pauleveritt** [MoonshotProject/moondash#61]
In src/mockapi I do require('url') which adds the NodeJS url package to moondash.js. It's not small. Since it is only used in with-mocks.js can it be only included in the file and not moondash.js?

If not, can we get it into moondash-vendors? (Next ticket coming about that.)

**Comment by ebrehault** [comment]
Fixed by https://github.com/MoonshotProject/moondash/commit/b5aef378b6d73d98ec3e604da6b12732581a9d28

**Comment by ebrehault** [comment]
My solution does not work.
We cannot just put it in vendors because this package actually use `require`, so it has to be processed by `browserify`.
So we need to create a new browserified bundle that would contain all the CommonJS-compliant vendor libs, and this bundle would then be concatenated with our current non-CommonJS vendors bundle.

**Comment by pauleveritt** [comment]
Let’s leave it at the status quo then. It’s not the end of the world if moondash.js is a little bigger. Later, when we minify it, then it will just be small noise.

—Paul
